# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
description: >- # this means to ignore newlines until "baseurl:"
  Welcome! Our conference includes great research papers on a variety of 
  CS education topics, tutorials and workshops on classroom techniques, 
  and research poster. We are also looking forward to showcasing student 
  research with both papers and posters.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://ccsc-midsouth.github.io" # the base hostname & protocol for your site, e.g. http://example.com

number: CCSC-MS
title: CCSC Midsouth
semester: Spring 2026
hypothesis: false

navigation:
  - title: Overview
    subfolderitems:
      - page: Description
        url: '#description'
      - page: Learning Goals
        url: '#goals'
      - page: Resources
        url: '#resources'
  - page: In-Class Code
    url: '#inclasscode'
  - title: Coursework
    subfolderitems:
      - page: Homework and Quizzes
        url: '#hwqz'
      - page: Labs
        url: '#labs'
      - page: Projects
        url: '#projects'
      - page: Exams
        url: '#exams'
      - page: Scale
        url: '#scale'
  - page: Commitments
    url: '#commitments'

hosts:
  - id: lipscomb
    name: Lipscomb University
    web: https://lipscomb.edu/

offerings:
  - loc: Nashville, TN
    time: April 12-13, 2026
    host: lipscomb

resources:
  - name: Rephactor
    image: assets/images/rephactor-logo.png
    url: https://rephactor.com
  - name: ACM2y
    image: assets/images/acm2y-logo_a.jpg
    url: https://acm2y.acm.org
  - name: GitHub
    image: assets/images/GitHub-logo.png
    url: https://github.com
  - name: CodeGrade
    image: assets/images/CodeGrade-logo.png
    url: https://codegrade.com
  - name: CodeZinger
    image: assets/images/codezinger-logo.png
    url: https://codezinger.com
# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
