# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
description: >- # this means to ignore newlines until "baseurl:"
  Welcome! The CCSC:MidSouth Conference is a regional conference sponsored by the Consortium for Computing
  Sciences in Colleges and is designed to promote exchange of information among college personnel
  concerned with computer use in the academic environment. It is intended for faculty as well as
  administrators of academic computing facilities, and it is also intended to be welcoming to student
  participants in a variety of special activities. Because personnel at teaching-oriented colleges often have
  restricted travel budgets, the scheduling of regional conferences of the CCSC is done with consideration
  toward minimizing conference costs. The conference is held in cooperation with SIGCSE. Submitted papers are refereed, 
  with those that are accepted being published in the (ACM recognized) Journal of Computing Sciences in Colleges.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://ccsc-midsouth.github.io" # the base hostname & protocol for your site, e.g. http://example.com

number: CCSC-MS
title: CCSC Midsouth
semester: Spring 2026
hypothesis: false
participation: true
program: false
registration: false

navigation:
  - page: Overview
    url: '#overview'
  - title: Submit
    subfolderitems:
      - page: Papers
        url: '#cfp'
      - page: Panels
        url: '#cfp'
      - page: Tutorials
        url: '#cfp'
      - page: Workshops
        url: '#cfp'
      - page: Posters
        url: '#cfp'
#  - page: Register
#    url: '#registration'
#  - page: Program
#    url: '#program'
  - page: Travel
    url: '#travel'
  - page: Organizers
    url: '#committee'

hosts:
  - id: lipscomb
    name: Lipscomb University
    web: https://lipscomb.edu/

offerings:
  - id: 2026
    loc: Nashville, TN
    time: April 10-11, 2026
    host: lipscomb

resources:
  - name: Rephactor
    image: assets/images/rephactor-logo.png
    url: https://rephactor.com
  - name: ACM2y
    image: assets/images/acm2y-logo_a.jpg
    url: https://acm2y.acm.org
  - name: GitHub
    image: assets/images/GitHub-logo.png
    url: https://github.com
  - name: CodeGrade
    image: assets/images/CodeGrade-logo.png
    url: https://codegrade.com
  - name: CodeZinger
    image: assets/images/codezinger-logo.png
    url: https://codezinger.com
# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
